[package]
name = "bifrost-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "bifrost-tui"
path = "src/main.rs"

[dependencies]
bifrost-core.workspace = true
bifrost-config.workspace = true
bifrost-client.workspace = true
ratatui.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }
